SELECT *
FROM WAGONS
INNER JOIN 
	(SELECT TRAINS.ID
	FROM TRAINS
	INNER JOIN TRAIN_ROUTE_CONNECTION 
		ON TRAINS.ID = TRAIN_ROUTE_CONNECTION.TRAINS_ID
	INNER JOIN 
		(SELECT ROUTE_STATIONS_CONNECTION.ROUTES_ID , SUM(ROUTE_STATIONS_CONNECTION.EXPLETIVE_TICKET) AS 'TMP3_EXPLETIVE_TICKET'
			FROM ROUTE_STATIONS_CONNECTION
			INNER JOIN
				(SELECT *
				FROM ROUTE_STATIONS_CONNECTION 
				INNER JOIN STATIONS ON ROUTE_STATIONS_CONNECTION.STATIONS_ID = STATIONS.ID
				INNER JOIN 
					(SELECT STATION_INDEX_IN_ROUTE AS 'TMP2_STATION_INDEX_IN_ROUTE', ROUTES_ID AS 'TMP2_ROUTES_ID'
					FROM ROUTE_STATIONS_CONNECTION
					INNER JOIN STATIONS ON ROUTE_STATIONS_CONNECTION.STATIONS_ID = STATIONS.ID
					WHERE STATIONS.NAME = 'Ajak') TMP2
					ON ROUTE_STATIONS_CONNECTION.ROUTES_ID = TMP2.TMP2_ROUTES_ID
				WHERE STATIONS.NAME = 'Kisvárda' AND TMP2.TMP2_STATION_INDEX_IN_ROUTE > ROUTE_STATIONS_CONNECTION.STATION_INDEX_IN_ROUTE) TMP 
				ON ROUTE_STATIONS_CONNECTION.ROUTES_ID = TMP.ROUTES_ID
			WHERE ROUTE_STATIONS_CONNECTION.STATION_INDEX_IN_ROUTE BETWEEN TMP.STATION_INDEX_IN_ROUTE AND TMP.TMP2_STATION_INDEX_IN_ROUTE
			GROUP BY ROUTE_STATIONS_CONNECTION.ROUTES_ID) TMP3
		ON TRAIN_ROUTE_CONNECTION.ROUTES_ID = TMP3.ROUTES_ID
	WHERE DATE(TRAIN_ROUTE_CONNECTION.START) = DATE('2016-12-02') AND TRAIN_ROUTE_CONNECTION.START > NOW() AND TMP3.TMP3_EXPLETIVE_TICKET = 0) TMP4
	ON TMP4.ID = WAGONS.TRAINS_ID
INNER JOIN (SELECT TRAINS_ID, group_concat(CASE WHEN CLASS = 1 THEN SERVICES END separator ';') AS 'CLASS1_SERVICES'
			FROM WAGONS
			GROUP BY WAGONS.TRAINS_ID) TMP5
			ON WAGONS.TRAINS_ID = TMP5.TRAINS_ID
INNER JOIN (SELECT TRAINS_ID, group_concat(CASE WHEN CLASS = 2 THEN SERVICES END separator ';') AS 'CLASS2_SERVICES'
			FROM WAGONS
			GROUP BY WAGONS.TRAINS_ID) TMP6
			ON WAGONS.TRAINS_ID = TMP6.TRAINS_ID
GROUP BY WAGONS.TRAINS_ID;