SELECT *
FROM TRAINS
INNER JOIN TRAIN_ROUTE_CONNECTION 
	ON TRAINS.ID = TRAIN_ROUTE_CONNECTION.TRAINS_ID
INNER JOIN
	(SELECT *
	FROM ROUTE_STATIONS_CONNECTION 
	INNER JOIN STATIONS ON ROUTE_STATIONS_CONNECTION.STATIONS_ID = STATIONS.ID
	INNER JOIN (SELECT STATION_INDEX_IN_ROUTE AS 'TMP_STATION_INDEX_IN_ROUTE', ROUTES_ID AS 'TMP2_ROUTES_ID'
				FROM ROUTE_STATIONS_CONNECTION
				INNER JOIN STATIONS ON ROUTE_STATIONS_CONNECTION.STATIONS_ID = STATIONS.ID
				WHERE STATIONS.NAME = 'Ajak') TMP2
				ON ROUTE_STATIONS_CONNECTION.ROUTES_ID = TMP2.TMP2_ROUTES_ID
	WHERE STATIONS.NAME = 'Kisvárda' AND TMP2.TMP_STATION_INDEX_IN_ROUTE > ROUTE_STATIONS_CONNECTION.STATION_INDEX_IN_ROUTE) TMP 
	ON TRAIN_ROUTE_CONNECTION.ROUTES_ID = TMP.ROUTES_ID
WHERE DATE(TRAIN_ROUTE_CONNECTION.START) = DATE('2016-11-30') AND TRAIN_ROUTE_CONNECTION.START > NOW();
