CREATE TABLE ROUTES_TMP 
SELECT ROUTE_STATIONS_CONNECTION.ROUTES_ID, STATIONS.NAME, ROUTE_STATIONS_CONNECTION.STATION_INDEX_IN_ROUTE
FROM ROUTE_STATIONS_CONNECTION
INNER JOIN ROUTES ON ROUTES.ID = ROUTE_STATIONS_CONNECTION.ROUTES_ID
INNER JOIN STATIONS ON STATIONS.ID = ROUTE_STATIONS_CONNECTION.STATIONS_ID
WHERE STATIONS.NAME = 'Kisvárda' OR STATIONS.NAME = 'Ajak';
	
CREATE TABLE GOOD_ROUTES
SELECT ROUTES_TMP1.ROUTES_ID
FROM ROUTES_TMP AS ROUTES_TMP1
INNER JOIN (
SELECT ROUTES_TMP2.ROUTES_ID AS ROUTES_ID, MAX( ROUTES_TMP2.STATION_INDEX_IN_ROUTE ) AS STATION_INDEX_IN_ROUTE
FROM ROUTES_TMP AS ROUTES_TMP2
GROUP BY ROUTES_TMP2.ROUTES_ID
)table2 ON ROUTES_TMP1.ROUTES_ID = table2.ROUTES_ID
AND ROUTES_TMP1.STATION_INDEX_IN_ROUTE = table2.STATION_INDEX_IN_ROUTE
WHERE ROUTES_TMP1.NAME =  'Ajak';

SELECT *
FROM ROUTE_STATIONS_CONNECTION
INNER JOIN STATIONS
ON ROUTE_STATIONS_CONNECTION.STATIONS_ID = STATIONS.ID
WHERE ROUTE_STATIONS_CONNECTION.ROUTES_ID IN (SELECT * FROM GOOD_ROUTES);

SELECT * 
FROM ROUTE_STATIONS_CONNECTION 
INNER JOIN TRAIN_ROUTE_CONNECTION 
ON ROUTE_STATIONS_CONNECTION.ROUTES_ID = TRAIN_ROUTE_CONNECTION.ROUTES_ID 
INNER JOIN TRAINS
ON TRAIN_ROUTE_CONNECTION.TRAINS_ID = TRAINS.ID
WHERE ROUTE_STATIONS_CONNECTION.ROUTES_ID IN (SELECT * FROM GOOD_ROUTES) AND DATE(TRAIN_ROUTE_CONNECTION.START) = DATE('2016-11-30') AND ROUTE_STATIONS_CONNECTION.STATIONS_ID IN (SELECT STATIONS.ID FROM STATIONS WHERE STATIONS.NAME = 'Kisvárda');

DROP TABLE ROUTES_TMP;
DROP TABLE GOOD_ROUTES;